name: Publish Release

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  build_release:
    uses: Nivaes/Nivaes.Workflows/.github/workflows/basic_lib_publish_release.yaml@develop
